# Generated by Django 5.2.10 on 2026-01-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(help_text='Original product ID from spreadsheet', max_length=50, unique=True)),
                ('ean', models.CharField(blank=True, help_text='EAN barcode', max_length=50)),
                ('original_name', models.CharField(help_text='Original product name from spreadsheet', max_length=500)),
                ('worten_name', models.CharField(blank=True, help_text='Product name on Worten', max_length=500, null=True)),
                ('worten_url', models.URLField(blank=True, help_text='Product URL on Worten', max_length=1000, null=True)),
                ('lowest_price', models.DecimalField(blank=True, decimal_places=2, help_text='Lowest price found', max_digits=10, null=True)),
                ('seller_name', models.CharField(blank=True, help_text='Seller with lowest price', max_length=200, null=True)),
                ('is_available', models.BooleanField(default=False, help_text='Product availability on Worten')),
                ('last_scraped', models.DateTimeField(blank=True, help_text='Last scrape timestamp', null=True)),
                ('scrape_error', models.TextField(blank=True, help_text='Error message if scraping failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['original_id'],
            },
        ),
    ]
